apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-ml-backend
  namespace: staging
  labels:
    app: quantum-ml-backend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quantum-ml-backend
  template:
    metadata:
      labels:
        app: quantum-ml-backend
        environment: staging
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-username/quantumexp-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "true"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: CORS_ORIGINS
          value: "http://localhost:3000,https://staging.quantumexp.com"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: quantum-ml-backend-service
  namespace: staging
spec:
  selector:
    app: quantum-ml-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-ml-frontend
  namespace: staging
  labels:
    app: quantum-ml-frontend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quantum-ml-frontend
  template:
    metadata:
      labels:
        app: quantum-ml-frontend
        environment: staging
    spec:
      containers:
      - name: frontend
        image: ghcr.io/your-username/quantumexp-frontend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: quantum-ml-frontend-service
  namespace: staging
spec:
  selector:
    app: quantum-ml-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
