name: Code Quality and Formatting

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        cd backend
        pip install black flake8 isort mypy bandit
        pip install -r requirements.txt
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Python code formatting check
      run: |
        cd backend
        black --check --diff .
        isort --check-only --diff .
        
    - name: Python linting
      run: |
        cd backend
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Python type checking
      run: |
        cd backend
        mypy . --ignore-missing-imports --no-strict-optional
        
    - name: Python security check
      run: |
        cd backend
        bandit -r . -f json -o bandit-report.json || echo "Security issues found"
        
    - name: JavaScript/React linting
      run: |
        npm run lint || echo "No lint script found"
        
    - name: JavaScript/React formatting
      run: |
        npm run format:check || echo "No format check script found"
        
    - name: Upload code quality reports
      uses: actions/upload-artifact@v3
      with:
        name: code-quality-reports
        path: |
          backend/bandit-report.json

  auto-format:
    name: Auto-format Code
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        cd backend
        pip install black isort
        
    - name: Install Node.js dependencies
      run: npm ci
      
    - name: Auto-format Python code
      run: |
        cd backend
        black .
        isort .
        
    - name: Auto-format JavaScript/React code
      run: |
        npm run format || echo "No format script found"
        
    - name: Create Pull Request with formatted code
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'style: auto-format code'
        title: 'Auto-format code'
        body: 'This PR contains automatically formatted code.'
        branch: auto-format
        delete-branch: true
