name: Dependency Updates and Security

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Update Python dependencies
      run: |
        cd backend
        pip install --upgrade pip
        pip install pip-tools
        pip-compile --upgrade requirements.in || echo "No requirements.in found"
        
    - name: Update Node.js dependencies
      run: |
        npm update
        npm audit fix --force || echo "Audit fix failed, continuing..."
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated dependency updates'
        body: |
          This PR contains automated dependency updates.
          
          ## Changes
          - Updated Python dependencies
          - Updated Node.js dependencies
          - Applied security fixes
          
          Please review and test before merging.
        branch: dependency-updates
        delete-branch: true

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Python security audit
      run: |
        cd backend
        pip install safety
        safety check --json --output safety-report.json || echo "Security issues found"
        
    - name: Node.js security audit
      run: |
        npm audit --audit-level moderate --json > npm-audit-report.json || echo "Security issues found"
        
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          backend/safety-report.json
          npm-audit-report.json
